name: Packaging

on: [push, pull_request]

jobs:
 
  windows:
    runs-on: windows-latest
    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - arch: x86_64
            prefix: mingw-w64-x86_64
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          release: false
          update: true
          install: >-
            ${{ matrix.prefix }}-ca-certificates
            ${{ matrix.prefix }}-gettext-tools
            ${{ matrix.prefix }}-gtk4
            ${{ matrix.prefix }}-libadwaita
            ${{ matrix.prefix }}-python-build
            ${{ matrix.prefix }}-python-cx-freeze
            ${{ matrix.prefix }}-python-gobject
            ${{ matrix.prefix }}-python-pycodestyle
            ${{ matrix.prefix }}-python-pylint
            ${{ matrix.prefix }}-python-setuptools
            ${{ matrix.prefix }}-python-wheel
            ${{ matrix.prefix }}-webp-pixbuf-loader

      - name: Install additional dependencies
        run: python3 packaging/windows/dependencies.py

      - name: Freeze application
        run: python3 packaging/windows/setup.py bdist_msi

      - name: Archive installer artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ matrix.arch }}-installer
          path: packaging/windows/build/*.msi

      - name: Archive package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ matrix.arch }}-package
          path: packaging/windows/build/package
